version: 2

executorType: docker

containerInfo:
  - image: makkke/node

stages:
  build:
    workDir: ~/road-so-far-app
    steps:
      - type: checkout
      # Install Node.js dependencies
      - type: shell
        shell: /bin/bash
        command: yarn install
      # Run linting
      - type: shell
        shell: /bin/bash
        command: yarn lint
      # Run testing
      - type: shell
        shell: /bin/bash
        command: yarn test
      # Build
      - type: shell
        shell: /bin/bash
        command: yarn build

      # Deploy to production
      - type: deploy
        shell: /bin/bash
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            aws s3 sync ./public s3://app.roadsofar.com/ --delete
          fi
